// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQr3gh8WADZTkmTuBEq6FOV1QZIDz2uJU',
    appId: '1:778352522121:web:9c82bf3dc44150ac3b6758',
    messagingSenderId: '778352522121',
    projectId: 'agentk-980c8',
    authDomain: 'agentk-980c8.firebaseapp.com',
    databaseURL: 'https://agentk-980c8.firebaseio.com',
    storageBucket: 'agentk-980c8.firebasestorage.app',
    measurementId: 'G-B3PZ23VE2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsGsmhY9IN1SwlwoGQlKev1U7R8ax_6IE',
    appId: '1:778352522121:android:a00df5d4633055f03b6758',
    messagingSenderId: '778352522121',
    projectId: 'agentk-980c8',
    databaseURL: 'https://agentk-980c8.firebaseio.com',
    storageBucket: 'agentk-980c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN5SVK2ynM-iSJUBtBo_yJT6QLiO83Bo4',
    appId: '1:778352522121:ios:43cdbb40d0c37b5d3b6758',
    messagingSenderId: '778352522121',
    projectId: 'agentk-980c8',
    databaseURL: 'https://agentk-980c8.firebaseio.com',
    storageBucket: 'agentk-980c8.firebasestorage.app',
    androidClientId: '778352522121-v12ms3eobjli8l08hic0rrc3h17qeg63.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN5SVK2ynM-iSJUBtBo_yJT6QLiO83Bo4',
    appId: '1:778352522121:ios:43cdbb40d0c37b5d3b6758',
    messagingSenderId: '778352522121',
    projectId: 'agentk-980c8',
    databaseURL: 'https://agentk-980c8.firebaseio.com',
    storageBucket: 'agentk-980c8.firebasestorage.app',
    androidClientId: '778352522121-v12ms3eobjli8l08hic0rrc3h17qeg63.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQr3gh8WADZTkmTuBEq6FOV1QZIDz2uJU',
    appId: '1:778352522121:web:b3277c23988bc7983b6758',
    messagingSenderId: '778352522121',
    projectId: 'agentk-980c8',
    authDomain: 'agentk-980c8.firebaseapp.com',
    databaseURL: 'https://agentk-980c8.firebaseio.com',
    storageBucket: 'agentk-980c8.firebasestorage.app',
    measurementId: 'G-KS9TD5N38F',
  );
}
